version: '3.8'

services:
  frontend:
    build:
      context: fin-note-frontend
      dockerfile: Dockerfile
    ports:
      - "2405:80"
    volumes:
      - ./fin-note-frontend/src:/app/src
    environment:
      - NODE_ENV=development
    restart: always
